---
essential_packages:
  - ufw
  - hd-idle # for disk spindown
  - fwupd # for firmware updates
  - mergerfs # for mounting pools
  - python3-venv # for cache_mover dependencies
  - rsnapshot # for backup of data on ssd cache to hdds
  - powertop # for c-states checking
  - intel-gpu-tools # for intel_gpu_top to see gpu transcoding activity
  - smartmontools # for disk health reports
  # - radvd # for netowork RDNSS override # HACK: Temporary fix for ISP router

beszel_agent_image: "henrygd/beszel-agent-intel:latest"

essential_firewall_allowed_tcp_udp_ports:
  - port: 22
    proto: tcp
    comment: "SSH"

services_list:
  - authelia
  - bazarr
  - beszel-agent
  - beszel
  - cwa
  - cwad
  - docker-proxy
  - dozzle
  - flaresolverr
  - gluetun
  - gotenberg
  - homepage
  - jellyfin
  - jellyseerr
  - lldap
  - ntfy
  - paperless
  - postgres
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - redis
  - sablier
  - samba
  - sonarr
  - syncthing
  - tika
  - traefik
  # - wud
  - diun
