---
dependencies:
  - role: geerlingguy.security
    vars:
      security_ssh_port: "{{ common_security_ssh_port }}"
      security_ssh_password_authentication:
        "{{ common_security_ssh_password_authentication }}"
      security_ssh_allowed_users:
        - "{{ common_security_ssh_allowed_user }}"
      security_ssh_restart_handler_state: started
      security_sudoers_passwordless: "{{ common_security_sudoer_passwordless }}"
      security_autoupdate_reboot: "{{ common_security_autoupdate_reboot }}"
      security_autoupdate_reboot_time: "{{ common_security_autoupdate_reboot_time }}"
      security_fail2ban_enabled: false
    tags: [external]

  - name: geerlingguy.pip
    vars:
      pip_install_packages: "{{ common_pip_install_packages }}"
    tags: [external]

  - name: geerlingguy.docker
    vars:
      docker_users:
        - "{{ common_docker_user }}"
      docker_daemon_options: "{{ common_docker_daemon_options }}"
    tags: [external]
