---
common_user: OverrideMeInGroupVars
common_ssh_port: OverrideMeInGroupVars

# general.yml
common_x11_variant: OverrideMeInGroupVars

# packages.yml
common_packages:
  - ufw

# firewall.yml
common_firewall_reset: false
common_firewall_allowed_tcp_udp_ports:
  - port: "{{ common_ssh_port }}"
    proto: tcp
    comment: "SSH"

# network.yml
common_network_lan:
  interface: OverrideMeInGroupVars
  ipv4:
    addr: OverrideMeInGroupVars
    cidr: OverrideMeInGroupVars
    router: OverrideMeInGroupVars
    dns: OverrideMeInGroupVars
  ipv6:
    addr: OverrideMeInGroupVars
    cidr: OverrideMeInGroupVars
    dns: OverrideMeInGroupVars

# geerlingguy.security
common_security_ssh_port: "{{ common_ssh_port }}"
common_security_ssh_password_authentication: "no"
common_security_ssh_allowed_user: "{{ common_user }}"
common_security_sudoer_passwordless: "{{ common_user }}"
common_security_autoupdate_reboot: true
common_security_autoupdate_reboot_time: 06:00

# geerlingguy.pip
common_pip_install_packages:
  - name: docker

# geerlingguy.docker
common_docker_user: "{{ common_user }}"
common_docker_daemon_options:
  icc: false
