---
- name: packages | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [essential, packages]

- name: packages | Upgrade packages
  ansible.builtin.apt:
    upgrade: dist
  tags: [essential, packages]

- name: packages | Install packages
  ansible.builtin.apt:
    name: "{{ essential_packages }}"
  tags: [essential, packages]
