---
common_packages:
  - ufw
  - fwupd # for firmware updates
  - hd-idle # for disk spindown
  - mergerfs # for mounting pools
  - python3-venv # for cache_mover dependencies
  - rsnapshot # for backup of data on ssd cache to hdds
  - powertop # for c-states checking
  - intel-gpu-tools # for intel_gpu_top to see gpu transcoding activity
  - smartmontools # for disk health reports

common_x11_variant: nodeadkeys

common_firewall_allowed_tcp_udp_ports:
  - port: "{{ common_ssh_port }}"
    proto: tcp
    comment: "SSH"

common_network_lan:
  interface: enp0s31f6
  ipv4:
    addr: 192.168.0.100
    cidr: /24
    router: 192.168.0.1
    dns: 192.168.0.99
  ipv6:
    addr: fd42:1234:5678::2
    cidr: /64
    dns: fd42:1234:5678::1

container_beszel_agent_image: "henrygd/beszel-agent-intel:latest"

container_dozzle_hostname: homeserver
container_dozzle_remote_agent: "netserver.lan:7007"

container_list:
  - audiobookshelf
  - authelia
  - bazarr
  - beszel-agent
  - beszel
  - cwa
  - diun
  - docker-proxy
  - dozzle
  - flaresolverr
  - gluetun
  - gotenberg
  - homepage
  - jellyfin
  - jellyseerr
  - lldap
  - ntfy
  - paperless
  - postgres
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - redis
  - sablier
  - samba
  - shelfmark
  - sonarr
  - syncthing
  - tika
  - traefik
