---
common_packages:
  - ufw
  - fwupd # for firmware updates
  - hd-idle # for disk spindown
  - snapraid # for hdd parity
  - mergerfs # for mounting pools
  - python3-venv # for cache_mover dependencies
  - rsnapshot # for backup of data on ssd cache to hdds
  - powertop # for c-states checking
  - radeontop # for amd gpus to see hardware activity
  # - intel-gpu-tools # for intel_gpu_top to see gpu transcoding activity
  - smartmontools # for disk health reports

common_x11_variant: nodeadkeys

common_firewall_allowed_tcp_udp_ports:
  - port: "{{ common_ssh_port }}"
    proto: tcp
    comment: SSH

common_network_lan:
  interface: enp6s0 # enp0s31f6
  ipv4:
    addr: 10.40.0.10
    cidr: /24
    router: 10.40.0.1
    dns: 10.40.0.1

container_dozzle_hostname: homeserver

container_path_compose: /opt/docker/compose

container_list:
  - audiobookshelf
  - authelia
  - backrest
  - bazarr
  - beszel-agent
  - beszel
  - cwa
  - databasus
  - diun
  - docker-proxy
  - dozzle
  - flaresolverr
  - gluetun
  - freshrss
  - gotenberg
  - homepage
  - immich
  - jellyfin
  - jellyseerr
  - linkding
  - lldap
  - metube
  - navidrome
  - ntfy
  - paperless
  - pgadmin
  - podsync
  - postgres
  - prowlarr
  # - pyload
  - qbittorrent
  - radarr
  - recyclarr
  - redis
  - sablier
  - samba
  - shelfmark
  - sonarr
  - stirlingpdf
  - syncthing
  - tika
  - traefik
  - uptime-kuma
  - vaultwarden
