---
container_lan:
  dhcp_start: 192.168.0.150
  dhcp_end: 192.168.0.247
  router: 192.168.0.1
  netmask: 255.255.255.0

container_traefik_network:
  subnet: 172.25.0.0/16
  gateway: 172.25.0.1
  traefik: 172.25.255.254

container_bridge_networks:
  - diun
  - docker-proxy
  - flaresolverr
  - recyclarr
  - samba
  - traefik

container_internal_networks:
  - gotenberg
  - lldap
  - ntfy
  - postgres
  - redis
  - sablier
  - tika

container_webui_port:
  qbittorrent: 8112
  shelfmark: 8084
  radarr: 7878
  sonarr: 8989
  prowlarr: 9696
  bazarr: 6767
  jellyseerr: 5055
  jellyfin: 8096
  lldap: 17170
  cwa: 8083
  authelia: 9091
  beszel: 8090
  dozzle: 8080
  homepage: 3000
  ntfy: 2586
  paperless: 8000
  pihole: 443
  pyload: 8000
  syncthing: 8384
  audiobookshelf: 13378
