---
- name: Restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted
  tags: [common, general]

- name: Set LANG
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
  changed_when: true
  tags: [common, general]

- name: Apply Netplan config
  ansible.builtin.command: netplan apply
  changed_when: true
  tags: [common, pihole]

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  tags: [common, firewall]
