---
- name: dirs | Create local template dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ config_username }}"
    group: "{{ config_username }}"
  loop:
    - "{{ playbook_dir }}/.ansible/templates"
    - "{{ playbook_dir }}/.ansible/configs"
  delegate_to: localhost
  tags: [services, dirs]

- name: dirs | Create docker compose dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ config_username }}"
    group: "{{ config_username }}"
  loop:
    - "{{ config_path.compose }}"
  tags: [services, dirs]
