---
- name: Ensure dirs on boot drive exist
  ansible.builtin.include_tasks: dirs.yml
  tags: [config, dirs]

- name: Copy configuration files
  ansible.builtin.include_tasks: configs.yml
  tags: [config, configs]

- name: Build and copy recyclarr configuration
  ansible.builtin.include_tasks: recyclarr.yml
  tags: [config, recyclarr, recyclarr_noget]
