---
- name: dotfiles | Check if chezmoi is already installed
  ansible.builtin.stat:
    path: /home/{{ common_user }}/.local/bin/chezmoi
  register: common_chezmoi_bin
  tags: [common, dotfiles]

- name: dotfiles | Get chezmoi installer script
  ansible.builtin.get_url:
    url: https://get.chezmoi.io
    dest: /tmp/chezmoi.sh
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: "0755"
  when: not common_chezmoi_bin.stat.exists
  tags: [common, dotfiles]

- name: dotfiles | Run chezmoi install script
  ansible.builtin.command: >
    sh /tmp/chezmoi.sh -b /home/{{ common_user }}/.local/bin
  args:
    creates: /home/{{ common_user }}/.local/bin/chezmoi
  when: not common_chezmoi_bin.stat.exists
  tags: [common, dotfiles]

- name: dotfiles | Set ownership for chezmoi bin
  ansible.builtin.file:
    path: /home/{{ common_user }}/.local/bin/chezmoi
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
  tags: [common, dotfiles]
#
# TODO: Requires input for rbw (mail, password, 2fa)
# Normal command: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin init --apply sad1ee
# - name: dotfiles | Initialize and apply chezmoi dotfiles
#   ansible.builtin.command: >
#     "{{ ansible_env.HOME }}/.local/bin/chezmoi init --apply sad1ee"
#   args:
#     chdir: "{{ ansible_env.HOME }}"
#     creates: "{{ ansible_env.HOME }}/.config/chezmoi"
#   when: not common_chezmoi_bin.stat.exists
#   tags: [common, dotfiles]
