---
- name: Ensure basic system configuration
  ansible.builtin.include_tasks: general.yml
  tags: [common, general]

- name: Install apt packages
  ansible.builtin.include_tasks: packages.yml
  tags: [common, packages]

- name: Install chezmoi dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
  tags: [common, dotfiles]

- name: Configure network
  ansible.builtin.include_tasks: network.yml
  tags: [common, network]

- name: Configure UFW firewall
  ansible.builtin.include_tasks: firewall.yml
  tags: [common, firewall, ipv6]
