---
- name: Ensure drives are mounted
  ansible.builtin.import_tasks: mount_disks.yml
  tags: [homeserver, mount_disks]

- name: Ensure mergerfs-cache-mover is setup
  ansible.builtin.import_tasks: cache_mover.yml
  tags: [homeserver, cache_mover]

- name: Ensure HDD spindown is configured
  ansible.builtin.import_tasks: hdd_spindown.yml
  tags: [homeserver, spindown]

- name: Ensure hardware transcoding for jellyfin is configured
  ansible.builtin.import_tasks: transcoding.yml
  tags: [homeserver, transcoding]

- name: Ensure rsnapshot backups are configured
  ansible.builtin.import_tasks: backups.yml
  tags: [never, backup]
  # tags: [homeserver, backup]
