---
common_packages:
  - ufw
  - fwupd # for firmware updates

common_firewall_allowed_tcp_udp_ports:
  - port: "{{ common_ssh_port }}"
    proto: tcp
    comment: SSH
  - port: 53
    proto: tcp
    comment: Pihole DNS
  - port: 53
    proto: udp
    comment: Pihole DNS
  - port: 67
    proto: udp
    comment: Pihole DHCP
  - port: 123
    proto: udp
    comment: Pihole NTP
  - port: 443
    proto: tcp
    comment: Pihole Webui

common_network_lan:
  interface: eth0
  ipv4:
    addr: 192.168.0.99
    cidr: /24
    router: 192.168.0.1
    dns: 127.0.0.1
  ipv6:
    addr: fd42:1234:5678::1
    cidr: /64
    dns: fd42:1234:5678::1

container_beszel_agent_image: henrygd/beszel-agent:latest

container_dozzle_hostname: netserver

container_path_compose: /opt/docker/compose
container_path_docker: /opt/docker

container_list:
  - pihole
  - beszel-agent
  - dozzle-agent
