---
container_domain_base_seperated: "{{ container_domain_base | split('.') }}"

container_docker_proxy_host: "tcp://docker-proxy:2375"

container_netserver_domain: "netserver.lan"

container_user: "OverrideMeInGroupVars"
container_puid: "OverrideMeInGroupVars"
container_pgid: "OverrideMeInGroupVars"
container_tz: "OverrideMeInGroupVars"

container_list: "OverrideMeInGroupVars"

container_beszel_agent_image: "OverrideMeInGroupVars"

container_dozzle_hostname: "OverrideMeInGroupVars"
container_dozzle_remote_agent: "OverrideMeInGroupVars"
