---
container_path_ssd1: "/mnt/ssd1"
container_path_hdd_pool: "/mnt/hdd-pool"

container_path_compose: "/opt/docker/compose"
container_path_tmp: "/opt/docker/tmp"
container_path_docker: "/mnt/ssd1/docker"

container_path:
  media: "/mnt/storage/media"

  audiobookshelf:
    config: "{{ container_path_docker }}/audiobookshelf/config"
    metadata: "{{ container_path_docker }}/audiobookshelf/metadata"

  authelia: "{{ container_path_docker }}/authelia"

  backrest: "{{ container_path_docker }}/backrest"

  bazarr: "{{ container_path_docker }}/bazarr"

  beszel:
    data: "{{ container_path_docker }}/beszel/data"
    agent: "{{ container_path_docker }}/beszel/agent"

  calibre:
    config: "{{ container_path_docker }}/cwa"
    ingest: "{{ container_path_tmp }}/cwa-ingest"
    library: "{{ container_path_ssd1 }}/data/calibre-library"

  databasus: "{{ container_path_docker }}/databasus"

  diun: "{{ container_path_docker }}/diun"

  dozzle: "{{ container_path_docker }}/dozzle"

  homepage: "{{ container_path_docker }}/homepage"

  immich:
    ml: "{{ container_path_docker }}/immich/ml"
    db: "{{ container_path_docker }}/immich/db"
    data: "{{ container_path_ssd1 }}/data/immich-data"

  jellyfin: "{{ container_path_docker }}/jellyfin"

  jellyseerr: "{{ container_path_docker }}/jellyseerr"

  lldap: "{{ container_path_docker }}/lldap"

  metube: "{{ container_path_ssd1 }}/media/downloads"

  navidrome: "{{ container_path_docker }}/navidrome"

  ntfy: "{{ container_path_docker }}/ntfy"

  paperless:
    data: "{{ container_path_docker }}/paperless"
    media: "{{ container_path_ssd1 }}/data/paperless-data"
    trash: "{{ container_path_ssd1 }}/data/paperless-data/trash"
    consume: "{{ container_path_tmp }}/paperless-consume"
    export: "{{ container_path_tmp }}/paperless-export"

  pihole:
    pihole: "{{ container_path_docker }}/pihole/pihole"
    dnsmasq: "{{ container_path_docker }}/pihole/dnsmasq"

  postgres: "{{ container_path_docker }}/postgres/data"

  prowlarr: "{{ container_path_docker }}/prowlarr"

  pyload:
    config: "{{ container_path_docker }}/pyload/config"
    downloads: "{{ container_path_docker }}/pyload/downloads"

  qbittorrent: "{{ container_path_docker }}/qbittorrent"

  radarr: "{{ container_path_docker }}/radarr"

  recyclarr: "{{ container_path_docker }}/recyclarr"

  redis: "{{ container_path_docker }}/redis"

  samba: "/mnt/storage"

  shelfmark: "{{ container_path_docker }}/shelfmark"

  sonarr: "{{ container_path_docker }}/sonarr"

  syncthing:
    config: "{{ container_path_docker }}/syncthing"
    data: "{{ container_path_ssd1 }}/data/syncthing-data"

  traefik: "{{ container_path_docker }}/traefik"
