---
# *********************************************************************************** #
# ******************************* Override in secrets ******************************* #
# *********************************************************************************** #

container_domain_base: "OverrideMeInSecrets"

# Beszel-agent
container_beszel_key: "OverrideMeInSecrets"
container_beszel_token: "OverrideMeInSecrets"

# CWA
container_cwa_hardcover_token: "OverrideMeInSecrets"

# Diun
container_diun_ntfy_token: "OverrideMeInSecrets"

# Gluetun
container_gluetun_openvpn_user: "OverrideMeInSecrets"
container_gluetun_openvpn_password: "OverrideMeInSecrets"
container_gluetun_protonvpn_email: "OverrideMeInSecrets"
container_gluetun_protonvpn_password: "OverrideMeInSecrets"

# LLDAP
container_lldap_jwt_secret: "OverrideMeInSecrets"
container_lldap_key_seed: "OverrideMeInSecrets"

# NTFY
container_ntfy_auth_users: "OverrideMeInSecrets"

# Pihole
container_pihole_pass: "OverrideMeInSecrets"
container_pihole_dhcp_hosts: ["OverrideMeInSecrets"]
container_pihole_dns_hosts: ["OverrideMeInSecrets"]
container_pihole_cname_records: ["OverrideMeInSecrets"]

# Postgres
container_jellyseerr_db_pass: "OverrideMeInSecrets"
container_lldap_db_pass: "OverrideMeInSecrets"
container_paperless_db_pass: "OverrideMeInSecrets"
container_postgres_db_pass: "OverrideMeInSecrets"

# Samba
container_samba_user: "OverrideMeInSecrets"
container_samba_pass: "OverrideMeInSecrets"

# Traefik
container_cf_dns_api_token: "OverrideMeInSecrets"

# Authelia oidc clients
container_authelia_client_secret_paperless_plain: "OverrideMeInSecrets"
