services:
  npm:
    image: "jc21/nginx-proxy-manager:latest"

    environment:
      PUID: "{{ container_puid }}"
      PGID: "{{ container_pgid }}"
      TZ: "{{ container_timezone }}"
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_NAME: "npm"
      DB_POSTGRES_USER: "npm"
      DB_POSTGRES_PASSWORD: "{{ container_npm_db_pass }}"

    volumes:
      - "{{ container_path.npm.data }}:/data"
      - "{{ container_path.npm.letsencrypt }}:/etc/letsencrypt"
      - "{{ container_path.npm.snippets }}:/snippets"

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      postgres:
        condition: "service_healthy"

    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: "60s"
      timeout: "30s"
      retries: "3"
      start_period: "60s"
      start_interval: "5s"

    container_name: "npm"
    hostname: "npm"
    restart: "unless-stopped"

    networks:
      - "traefik"
      - "postgres"
