services:
  pyload:
    image: "lscr.io/linuxserver/pyload-ng:latest"

    labels:
      traefik.enable: true
      traefik.http.routers.pyload.rule: Host(`pyload.{{ container_domain_base }}`)
      traefik.http.services.pyload.loadbalancer.server.port: "{{ container_webui_port.pyload }}"
      traefik.http.routers.pyload.middlewares: authelia@docker

    environment:
      PUID: "{{ container_puid }}"
      PGID: "{{ container_pgid }}"
      TZ: "{{ container_timezone }}"

    volumes:
      - "{{ container_path.pyload.config }}:/config"
      - "{{ container_path.pyload.downloads }}:/downloads"

    container_name: "pyload"
    hostname: "pyload"
    restart: "unless-stopped"

    networks:
      - "traefik"
