services:
  redis:
    image: "docker.io/library/redis:8"

    labels:
      dev.dozzle.group: "Backend"

    volumes:
      - "{{ container_path.redis }}:/data"
      - "/etc/localtime:/etc/localtime:ro"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "60s"
      timeout: "30s"
      retries: "3"
      start_period: "60s"
      start_interval: "5s"

    container_name: "redis"
    hostname: "redis"
    restart: "unless-stopped"

    networks:
      - "redis"
